### ISSUE TITLE
TypeError: ts_transformer_dates_1.toDates is not a function

### ISSUE THREAD

**Issue by gorn** [lduburas/ts-transformer-dates#14]
I get this error when trying to use it. Forgive my ignorance, but I fail to see where toDates is implemented. In `src/index.ts ` I see `export declare function toDates<T extends object>(value: any, converter?: Converter): T;` but it seems not to be implemented at all. What am I missing? Should I use another function thatn toDates? Currently I do:

```
import { toDates } from "ts-transformer-dates"

interface Range {
  dateFrom: Date
  dateTo: Date
  notes: string
}

const value = {
  dateFrom: "2020-01-12T03:25:45.000Z", // date as ISO string
  dateTo: 1578799545000, // date as number of milliseconds
  notes: "brown fox",
}

toDates<Range>(value)

```

i have it installed with `npm install ts-transformer-dates --save`

**Comment by lduburas** [comment]
I guess you are trying to run with:
`tsc sample.ts`
`node sample.js`
This will not work. The problem is that `tsc` doesn't support custom transformers. You should check the _example_ dir.` npm run` with given _webpack_ configuration will generate two runnable scripts _ts-loader.js_ and _awesome-typescript-loader.js_. Both of them  can be run with `node` and produce the same output.
